import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      {children}
      <nav>
        <h1 className="text-lg py-2 m-2">logo</h1>
        <ul><li>
          <a href="http://localhost:3000/about">About</a>
          </li>
          <li>
          <a href="#">Sign up</a>
          </li>
          </ul>

      </nav>
        </body>
      
    </html>
  )
}
